version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    ports:
      - 3306:3306
    networks:
      - mynetwork
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
      - MYSQL_USER=root
      - MYSQL_PASSWORD=pwd
      - MYSQL_ROOT_HOST="%"
    volumes:
      - /home/mysql/data:/var/lib/mysql


  spring_app:
    image: ${REGISTRY}:${BUILD_NUMBER}
    container_name: examen
    restart: on-failure
    networks:
      - mynetwork
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/stationSki?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
    ports:
      - "8089:8089"
    depends_on:
      - mysqldb

networks:
  mynetwork:
    driver: bridge
