version: "3.3"
services:
  mysqldb:
    container_name: mysqldb
    ports:
      - "3307:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    image: mysql:8
    restart: unless-stopped
    volumes:
      - /home/mysql/data:/var/lib/mysql


  spring_app:
    image: ${REGISTRY}:${BUILD_NUMBER}
    container_name: exam
    restart: on-failure
    ports:
      - 9096:9096
    depends_on:
      - mysqldb
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/stationSki?&createDatabaseIfNotExist=true&useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

